# Prefix roots and suffixes for GarbhaJyoti baby-name database.
# prefix: (key, display, tr, tr_esh, tr_cons, en_word, hi_word, ne_word, pgender, deity_or_None)
#   tr       = Devanagari transliteration spelling (explicit long vowels)
#   tr_esh   = spelling used before the -esh suffix (vowel length varies)
#   tr_cons  = spelling used before consonant-initial suffixes (e.g. jai -> jaya)
#   pgender  = m / f / n  (which suffix genders may attach)
PREFIXES = [
# ---- masculine deity roots ----
('har','Har','har','har','har','Vishnu','हरि','हरि','m','Vishnu'),
('shiv','Shiv','shiv','shiv','shiv','Shiva','शिव','शिव','m','Shiva'),
('ram','Ram','raam','ram','raam','Rama','राम','राम','m','Rama'),
('krishn','Krishn','kRShN','kRShN','kRShN','Krishna','कृष्ण','कृष्ण','m','Krishna'),
('gopal','Gopal','gopaal','gopaal','gopaal','Krishna','गोपाल','गोपाल','m','Krishna'),
('govind','Govind','govind','govind','govind','Vishnu','गोविन्द','गोविन्द','m','Vishnu'),
('madhav','Madhav','maadhav','maadhav','maadhav','Vishnu','माधव','माधव','m','Vishnu'),
('keshav','Keshav','keshav','keshav','keshav','Vishnu','केशव','केशव','m','Vishnu'),
('narayan','Narayan','naaraayaN','naaraayaN','naaraayaN','Vishnu','नारायण','नारायण','m','Vishnu'),
('dev','Dev','dev','dev','dev','god','देव','देव','m','Deva'),
('sur','Sur','sur','sur','sur','god','सुर','सुर','m','Deva'),
('ganesh','Ganesh','gaNesh','gaNesh','gaNesh','Ganesha','गणेश','गणेश','m','Ganesha'),
('surya','Surya','soorya','soorya','soorya','the sun','सूर्य','सूर्य','m','Surya'),
('indra','Indra','indra','indra','indra','Indra','इन्द्र','इन्द्र','m','Indra'),
('agni','Agni','agni','agni','agni','fire','अग्नि','अग्नि','m','Agni'),
('vayu','Vayu','vaayu','vaayu','vaayu','wind','वायु','वायु','m','Vayu'),
('varun','Varun','varuN','varuN','varuN','lord of waters','वरुण','वरुण','m','Varuna'),
('kuber','Kuber','kuber','kuber','kuber','lord of wealth','कुबेर','कुबेर','m','Kubera'),
('hanuman','Hanuman','hanumaan','hanumaan','hanumaan','Hanuman','हनुमान','हनुमान','m','Hanuman'),
('mohan','Mohan','mohan','mohan','mohan','Krishna','मोहन','मोहन','m','Krishna'),
('madan','Madan','madan','madan','madan','love','मदन','मदन','m','Kamadeva'),
('guru','Guru','guru','guru','guru','teacher','गुरु','गुरु','m',None),
('maha','Maha','mahaa','mah','mahaa','great','महा','महा','m',None),
('raj','Raj','raaj','raaj','raaj','king','राज','राज','m',None),
('amar','Amar','amar','amar','amar','immortal','अमर','अमर','m',None),
('ajay','Ajay','ajay','ajay','ajay','invincible','अजय','अजय','m',None),
('abhay','Abhay','abhay','abhay','abhay','fearless','अभय','अभय','m',None),
('vijay','Vijay','vijay','vijay','vijay','victory','विजय','विजय','m',None),
('jai','Jai','jai','jai','jaya','victory','जय','जय','m',None),
('dharam','Dharam','dharam','dharam','dharam','righteousness','धर्म','धर्म','m',None),
('karam','Karam','karam','karam','karam','grace','कृपा','कृपा','m',None),
('satya','Satya','satya','satya','satya','truth','सत्य','सत्य','n',None),
('bal','Bal','bal','bal','bal','strength','बल','बल','m',None),
('tej','Tej','tej','tej','tej','radiance','तेज','तेज','n',None),
('yash','Yash','yash','yash','yash','glory','यश','यश','n',None),
('dhan','Dhan','dhan','dhan','dhan','wealth','धन','धन','n',None),
('vir','Vir','veer','veer','veer','brave','वीर','वीर','m',None),
('sohan','Sohan','sohan','sohan','sohan','handsome','सोहन','सोहन','m',None),
('kishan','Kishan','kishan','kishan','kishan','Krishna','किशन','किशन','m','Krishna'),
('sundar','Sundar','sundar','sundar','sundar','beautiful','सुन्दर','सुन्दर','m',None),
# ---- feminine deity roots ----
('lakshmi','Lakshmi','lakshmee','lakshmee','lakshmee','Lakshmi','लक्ष्मी','लक्ष्मी','f','Lakshmi'),
('saraswati','Saraswati','sarasvatee','sarasvatee','sarasvatee','Saraswati','सरस्वती','सरस्वती','f','Saraswati'),
('parvati','Parvati','paarvatee','paarvatee','paarvatee','Parvati','पार्वती','पार्वती','f','Parvati'),
('uma','Uma','umaa','um','umaa','Parvati','उमा','उमा','f','Parvati'),
('gauri','Gauri','gauree','gauree','gauree','Parvati','गौरी','गौरी','f','Parvati'),
('durga','Durga','durgaa','durgaa','durgaa','Durga','दुर्गा','दुर्गा','f','Durga'),
('kali','Kali','kaalee','kaalee','kaalee','Kali','काली','काली','f','Kali'),
('sita','Sita','seetaa','seetaa','seetaa','Sita','सीता','सीता','f','Sita'),
('radha','Radha','raadhaa','raadhaa','raadhaa','Radha','राधा','राधा','f','Radha'),
('ganga','Ganga','gaMgaa','gaMgaa','gaMgaa','the Ganga','गंगा','गंगा','f','Ganga'),
('yamuna','Yamuna','yamunaa','yamunaa','yamunaa','the Yamuna','यमुना','यमुना','f','Yamuna'),
('narmada','Narmada','narmadaa','narmadaa','narmadaa','the Narmada','नर्मदा','नर्मदा','f',None),
('kaveri','Kaveri','kaaveree','kaaveree','kaaveree','the Kaveri','कावेरी','कावेरी','f',None),
# ---- neutral virtue / nature roots ----
('su','Su','su','su','su','good','सु','सु','n',None),
('prem','Prem','prem','prem','prem','love','प्रेम','प्रेम','n',None),
('anand','Anand','aanand','aanand','aanand','bliss','आनन्द','आनन्द','n',None),
('sukh','Sukh','sukh','sukh','sukh','happiness','सुख','सुख','n',None),
('shanti','Shanti','shaanti','shaanti','shaanti','peace','शान्ति','शान्ति','n',None),
('daya','Daya','dayaa','dayaa','dayaa','compassion','दया','दया','n',None),
('kshama','Kshama','kshamaa','kshamaa','kshamaa','forgiveness','क्षमा','क्षमा','n',None),
('karuna','Karuna','karuNaa','karuNaa','karuNaa','compassion','करुणा','करुणा','n',None),
('mamta','Mamta','mamtaa','mamtaa','mamtaa','affection','ममता','ममता','n',None),
('asha','Asha','aashaa','aashaa','aashaa','hope','आशा','आशा','n',None),
('kirti','Kirti','keerti','keerti','keerti','fame','कीर्ति','कीर्ति','n',None),
('gun','Gun','guN','guN','guN','virtue','गुण','गुण','n',None),
('sheel','Sheel','sheel','sheel','sheel','conduct','शील','शील','n',None),
('kala','Kala','kalaa','kalaa','kalaa','art','कला','कला','n',None),
('vidya','Vidya','vidyaa','vidyaa','vidyaa','learning','विद्या','विद्या','n',None),
('gyan','Gyan','gyaan','gyaan','gyaan','wisdom','ज्ञान','ज्ञान','n',None),
('geet','Geet','geet','geet','geet','song','गीत','गीत','n',None),
('jyoti','Jyoti','jyoti','jyoti','jyoti','light','ज्योति','ज्योति','n',None),
('deep','Deep','deep','deep','deep','lamp','दीप','दीप','n',None),
('chand','Chand','chand','chand','chand','the moon','चन्द्र','चन्द्र','n','Chandra'),
('suraj','Suraj','sooraj','sooraj','sooraj','the sun','सूरज','सूरज','n','Surya'),
('tara','Tara','taaraa','taaraa','taaraa','star','तारा','तारा','n',None),
('kamal','Kamal','kamal','kamal','kamal','lotus','कमल','कमल','n',None),
('padm','Padm','padm','padm','padm','lotus','पद्म','पद्म','n',None),
('pushp','Pushp','pushp','pushp','pushp','flower','पुष्प','पुष्प','n',None),
('kusum','Kusum','kusum','kusum','kusum','flower','कुसुम','कुसुम','n',None),
('suman','Suman','suman','suman','suman','flower','सुमन','सुमन','n',None),
('mallika','Mallika','mallikaa','mallikaa','mallikaa','jasmine','मल्लिका','मल्लिका','f',None),
('juhi','Juhi','joohee','joohee','joohee','jasmine','जूही','जूही','f',None),
('chameli','Chameli','chamelee','chamelee','chamelee','jasmine','चमेली','चमेली','f',None),
('neel','Neel','neel','neel','neel','blue','नील','नील','n',None),
('nirmal','Nirmal','nirmal','nirmal','nirmal','pure','निर्मल','निर्मल','n',None),
('vimal','Vimal','vimal','vimal','vimal','pure','विमल','विमल','n',None),
('amal','Amal','amal','amal','amal','pure','अमल','अमल','n',None),
('komal','Komal','komal','komal','komal','tender','कोमल','कोमल','n',None),
('atul','Atul','atul','atul','atul','matchless','अतुल','अतुल','n',None),
('som','Som','som','som','som','the moon','सोम','सोम','n','Chandra'),
('ravi','Ravi','ravi','ravi','ravi','the sun','रवि','रवि','n','Surya'),
('arun','Arun','aruN','aruN','aruN','dawn','अरुण','अरुण','n',None),
('him','Him','him','him','him','snow','हिम','हिम','n',None),
('shail','Shail','shail','shail','shail','mountain','शैल','शैल','n',None),
('sagar','Sagar','saagar','saagar','saagar','ocean','सागर','सागर','n',None),
('vasant','Vasant','vasant','vasant','vasant','spring','वसन्त','वसन्त','n',None),
('sharad','Sharad','sharad','sharad','sharad','autumn','शरद','शरद','n',None),
('megh','Megh','megh','megh','megh','cloud','मेघ','मेघ','n',None),
('varsha','Varsha','varshaa','varshaa','varshaa','rain','वर्षा','वर्षा','f',None),
('mor','Mor','mor','mor','mor','peacock','मोर','मोर','n',None),
('mayur','Mayur','mayoor','mayoor','mayoor','peacock','मयूर','मयूर','m',None),
('hans','Hans','haMs','haMs','haMs','swan','हंस','हंस','n',None),
('kokil','Kokil','kokil','kokil','kokil','cuckoo','कोकिल','कोकिल','n',None),
('chakor','Chakor','chakor','chakor','chakor','partridge','चकोर','चकोर','n',None),
('garud','Garud','garuD','garuD','garuD','eagle','गरुड़','गरुड़','m',None),
('shuk','Shuk','shuk','shuk','shuk','parrot','शुक','शुक','m',None),
('chatak','Chatak','chaatak','chaatak','chaatak','sarus bird','चातक','चातक','m',None),
('bulbul','Bulbul','bulbul','bulbul','bulbul','nightingale','बुलबुल','बुलबुल','f',None),
('moti','Moti','motee','motee','motee','pearl','मोती','मोती','n',None),
('heera','Heera','heeraa','heeraa','heeraa','diamond','हीरा','हीरा','n',None),
('ratna','Ratna','ratn','ratn','ratn','jewel','रत्न','रत्न','n',None),
('kanchan','Kanchan','kaMchan','kaMchan','kaMchan','gold','कंचन','कंचन','n',None),
('swarna','Swarna','svarNa','svarNa','svarNa','gold','स्वर्ण','स्वर्ण','n',None),
('hema','Hema','hemaa','hemaa','hemaa','golden','हेमा','हेमा','f',None),
('chandni','Chandni','chaa~danee','chaa~danee','chaa~danee','moonlight','चाँदनी','चाँदनी','f',None),
('roshni','Roshni','roshnee','roshnee','roshnee','light','रोशनी','रोशनी','f',None),
('khushi','Khushi','khushee','khushee','khushee','happiness','खुशी','खुशी','f',None),
('muskan','Muskan','muskaan','muskaan','muskaan','smile','मुस्कान','मुस्कान','f',None),
('aarti','Aarti','aartee','aartee','aartee','prayer offering','आरती','आरती','f',None),
('puja','Puja','poojaa','poojaa','poojaa','worship','पूजा','पूजा','f',None),
('archana','Archana','archanaa','archanaa','archanaa','worship','अर्चना','अर्चना','f',None),
('vandana','Vandana','vandanaa','vandanaa','vandanaa','praise','वन्दना','वन्दना','f',None),
('sadhana','Sadhana','saadhanaa','saadhanaa','saadhanaa','spiritual practice','साधना','साधना','f',None),
('bhakti','Bhakti','bhakti','bhakti','bhakti','devotion','भक्ति','भक्ति','f',None),
('shraddha','Shraddha','shraddhaa','shraddhaa','shraddhaa','faith','श्रद्धा','श्रद्धा','f',None),
('shobha','Shobha','shobhaa','shobhaa','shobhaa','splendor','शोभा','शोभा','f',None),
('naina','Naina','nainaa','nainaa','nainaa','eyes','नैना','नैना','f',None),
('kajal','Kajal','kaajal','kaajal','kaajal','kohl','काजल','काजल','f',None),
('payal','Payal','paayal','paayal','paayal','anklet','पायल','पायल','f',None),
('pankaj','Pankaj','paMkaj','paMkaj','paMkaj','lotus','पंकज','पंकज','m',None),
('jalaj','Jalaj','jalaj','jalaj','jalaj','lotus','जलज','जलज','m',None),
('saroj','Saroj','saroj','saroj','saroj','lotus','सरोज','सरोज','n',None),
('aravind','Aravind','aravind','aravind','aravind','lotus','अरविन्द','अरविन्द','m',None),
('rajiv','Rajiv','raajeev','raajeev','raajeev','lotus','राजीव','राजीव','m',None),
('nalini','Nalini','nalinee','nalinee','nalinee','lotus','नलिनी','नलिनी','f',None),
('kumudini','Kumudini','kumudinee','kumudinee','kumudinee','lotus','कुमुदिनी','कुमुदिनी','f',None),
('kumud','Kumud','kumud','kumud','kumud','lotus','कुमुद','कुमुद','n',None),
('yog','Yog','yog','yog','yog','union','योग','योग','n',None),
('din','Din','din','din','din','day','दिन','दिन','n',None),
('hit','Hit','hit','hit','hit','benefit','हित','हित','m',None),
('rakaa','Raka','raakaa','raak','raakaa','full moon','राका','राका','f',None),
('kaam','Kaam','kaam','kaam','kaam','desire','काम','काम','n',None),
('vyom','Vyom','vyom','vyom','vyom','sky','व्योम','व्योम','n',None),
('bhuvan','Bhuvan','bhuvan','bhuvan','bhuvan','world','भुवन','भुवन','n',None),
('akhil','Akhil','akhil','akhil','akhil','whole','अखिल','अखिल','m',None),
('nikhil','Nikhil','nikhil','nikhil','nikhil','whole','निखिल','निखिल','m',None),
('sarv','Sarv','sarv','sarv','sarv','all','सर्व','सर्व','n',None),
('nar','Nar','nar','nar','nar','man','नर','नर','m',None),
('ujjwal','Ujjwal','ujjval','ujjval','ujjval','bright','उज्ज्वल','उज्ज्वल','n',None),
('achyut','Achyut','achyut','achyut','achyut','Vishnu','अच्युत','अच्युत','m','Vishnu'),
('anant','Anant','anant','anant','anant','the endless one','अनन्त','अनन्त','m','Vishnu'),
('damodar','Damodar','daamodar','daamodar','daamodar','Krishna','दामोदर','दामोदर','m','Krishna'),
('janardan','Janardan','janaardan','janaardan','janaardan','Vishnu','जनार्दन','जनार्दन','m','Vishnu'),
('murari','Murari','muraari','muraari','muraari','Krishna','मुरारि','मुरारि','m','Krishna'),
('mukund','Mukund','mukund','mukund','mukund','Vishnu','मुकुन्द','मुकुन्द','m','Vishnu'),
('shankar','Shankar','shaMkar','shaMkar','shaMkar','Shiva','शंकर','शंकर','m','Shiva'),
('mahadev','Mahadev','mahaadev','mahaadev','mahaadev','Shiva','महादेव','महादेव','m','Shiva'),
('neelkanth','Neelkanth','neelkaNTh','neelkaNTh','neelkaNTh','Shiva','नीलकण्ठ','नीलकण्ठ','m','Shiva'),
('trilochan','Trilochan','trilochan','trilochan','trilochan','Shiva','त्रिलोचन','त्रिलोचन','m','Shiva'),
('pashupati','Pashupati','pashupati','pashupati','pashupati','Shiva','पशुपति','पशुपति','m','Shiva'),
('sudarshan','Sudarshan','sudarshan','sudarshan','sudarshan','Vishnu','सुदर्शन','सुदर्शन','m','Vishnu'),
('vaikunth','Vaikunth','vaikuNTh','vaikuNTh','vaikuNTh',"Vishnu's abode",'वैकुण्ठ','वैकुण्ठ','m','Vishnu'),
('srinivas','Srinivas','shreenivaas','shreenivaas','shreenivaas','Vishnu','श्रीनिवास','श्रीनिवास','m','Vishnu'),
('balram','Balram','balraam','balraam','balraam','Balarama','बलराम','बलराम','m','Balarama'),
('parshuram','Parshuram','parashuraam','parashuraam','parashuraam','Parashurama','परशुराम','परशुराम','m','Parashurama'),
('raghav','Raghav','raaghav','raaghav','raaghav','Rama','राघव','राघव','m','Rama'),
('kartik','Kartik','kaartik','kaartik','kaartik','Kartikeya','कार्तिक','कार्तिक','m','Kartikeya'),
('skand','Skand','skand','skand','skand','Kartikeya','स्कन्द','स्कन्द','m','Kartikeya'),
('maruti','Maruti','maaruti','maaruti','maaruti','Hanuman','मारुति','मारुति','m','Hanuman'),
('pavan','Pavan','pavan','pavan','pavan','the wind','पवन','पवन','m','Vayu'),
('anil','Anil','anil','anil','anil','the wind','अनिल','अनिल','m','Vayu'),
('meenakshi','Meenakshi','meenaakshee','meenaakshee','meenaakshee','Parvati','मीनाक्षी','मीनाक्षी','f','Parvati'),
('kamakshi','Kamakshi','kaamaakshee','kaamaakshee','kaamaakshee','Parvati','कामाक्षी','कामाक्षी','f','Parvati'),
('vishalakshi','Vishalakshi','vishaalaakshee','vishaalaakshee','vishaalaakshee','Parvati','विशालाक्षी','विशालाक्षी','f','Parvati'),
('annapurna','Annapurna','annapoorNaa','annapoorNaa','annapoorNaa','Parvati','अन्नपूर्णा','अन्नपूर्णा','f','Parvati'),
('bhairavi','Bhairavi','bhairavee','bhairavee','bhairavee','Durga','भैरवी','भैरवी','f','Durga'),
('vaishnavi','Vaishnavi','vaishNavee','vaishNavee','vaishNavee','Durga','वैष्णवी','वैष्णवी','f','Durga'),
('maheshwari','Maheshwari','maheshvaree','maheshvaree','maheshvaree','Parvati','महेश्वरी','महेश्वरी','f','Parvati'),
('punya','Punya','puNya','puNya','puNya','merit','पुण्य','पुण्य','n',None),
('tejas','Tejas','tejas','tejas','tejas','radiance','तेजस','तेजस','n',None),
('ojas','Ojas','ojas','ojas','ojas','vigor','ओजस','ओजस','n',None),
('manas','Manas','maanas','maanas','maanas','the mind','मानस','मानस','n',None),
('chetan','Chetan','chetan','chetan','chetan','consciousness','चेतन','चेतन','n',None),
('chaitanya','Chaitanya','chaitanya','chaitanya','chaitanya','consciousness','चैतन्य','चैतन्य','n',None),
('divya','Divya','divyaa','divyaa','divyaa','divine','दिव्या','दिव्या','n',None),
('bhavya','Bhavya','bhavya','bhavya','bhavya','grand','भव्य','भव्य','n',None),
('navya','Navya','navyaa','navyaa','navyaa','new','नव्या','नव्या','n',None),
('kavya','Kavya','kaavyaa','kaavyaa','kaavyaa','poetry','काव्या','काव्या','n',None),
('sahaj','Sahaj','sahaj','sahaj','sahaj','natural','सहज','सहज','n',None),
('achal','Achal','achal','achal','achal','steady','अचल','अचल','n',None),
]

# suffix: (key, display, tr, gender, en_t, hi_t, ne_t)
# {p} = english word, {ph} = hindi word, {pn} = nepali word
SUFFIXES = [
('dev','dev','dev','boy','divine {p}','दिव्य {ph}','दिव्य {pn}'),
('nath','nath','naath','boy','lord of {p}','{ph} नाथ','{pn} नाथ'),
('esh','esh','eesh','boy','lord of {p}','{ph} ईश','{pn} ईश'),
('prasad','prasad','prasaad','boy','blessing of {p}','{ph} प्रसाद','{pn} प्रसाद'),
('lal','lal','laal','boy','beloved of {p}','{ph} लाल','{pn} लाल'),
('kumar','kumar','kumaar','boy','prince of {p}','{ph} कुमार','{pn} कुमार'),
('chandra','chandra','chandra','boy','moonlike {p}','{ph} चन्द्र','{pn} चन्द्र'),
('dutt','dutt','datt','boy','given by {p}','{ph} दत्त','{pn} दत्त'),
('das','das','daas','boy','servant of {p}','{ph} दास','{pn} दास'),
('sharan','sharan','sharaN','boy','sheltered by {p}','{ph} शरण','{pn} शरण'),
('vallabh','vallabh','vallabh','boy','beloved of {p}','{ph} वल्लभ','{pn} वल्लभ'),
('kanta','kanta','kaanta','boy','beloved of {p}','{ph} कान्त','{pn} कान्त'),
('swaroop','swaroop','svaroop','boy','embodiment of {p}','{ph} स्वरूप','{pn} स्वरूप'),
('murti','murti','moorti','boy','embodiment of {p}','{ph} मूर्ति','{pn} मूर्ति'),
('shankar','shankar','shaMkar','boy','auspicious {p}','{ph} शंकर','{pn} शंकर'),
('bhakt','bhakt','bhakt','boy','devotee of {p}','{ph} भक्त','{pn} भक्त'),
('sevak','sevak','sevak','boy','servant of {p}','{ph} सेवक','{pn} सेवक'),
('raj','raj','raaj','boy','king of {p}','{ph} राज','{pn} राज'),
('priya','priya','priyaa','both','beloved of {p}','{ph} प्रिय','{pn} प्रिय'),
('maya','maya','maayaa','girl','full of {p}','{ph} मय','{pn} मय'),
('devi','devi','devee','girl','goddess of {p}','{ph} देवी','{pn} देवी'),
('vati','vati','vatee','girl','grace of {p}','{ph} वती','{pn} वती'),
('rani','rani','raanee','girl','queen of {p}','{ph} रानी','{pn} रानी'),
('kumari','kumari','kumaaree','girl','princess of {p}','{ph} कुमारी','{pn} कुमारी'),
('dasi','dasi','daasee','girl','devotee of {p}','{ph} दासी','{pn} दासी'),
('mala','mala','maalaa','girl','garland of {p}','{ph} माला','{pn} माला'),
('lata','lata','lataa','girl','vine of {p}','{ph} लता','{pn} लता'),
('bala','bala','baalaa','girl','young {p}','{ph} बाला','{pn} बाला'),
('shri','shri','shree','girl','radiant {p}','{ph} श्री','{pn} श्री'),
('dulari','dulari','dulaaree','girl','beloved of {p}','{ph} दुलारी','{pn} दुलारी'),
('pati','pati','pati','boy','lord of {p}','{ph} पति','{pn} पति'),
('pal','pal','paal','boy','protector of {p}','{ph} पाल','{pn} पाल'),
('veer','veer','veer','boy','heroic {p}','{ph} वीर','{pn} वीर'),
('jit','jit','jit','boy','victorious through {p}','{ph} से विजयी','{pn} बाट विजयी'),
('prakash','prakash','prakaash','boy','light of {p}','{ph} प्रकाश','{pn} प्रकाश'),
('anand','anand','aanand','boy','bliss of {p}','{ph} आनन्द','{pn} आनन्द'),
('nandan','nandan','nandan','boy','joy of {p}','{ph} नन्दन','{pn} नन्दन'),
('charan','charan','charaN','boy','at the feet of {p}','{ph} चरण','{pn} चरण'),
('ashish','ashish','aasheeSh','boy','blessing of {p}','{ph} आशीष','{pn} आशीष'),
('kishore','kishore','kishor','boy','youthful {p}','{ph} किशोर','{pn} किशोर'),
('lochan','lochan','lochan','boy','{p}-eyed','{ph} लोचन','{pn} लोचन'),
('prabha','prabha','prabhaa','girl','radiance of {p}','{ph} प्रभा','{pn} प्रभा'),
('kanti','kanti','kaanti','girl','radiance of {p}','{ph} कान्ति','{pn} कान्ति'),
('nandini','nandini','nandinee','girl','joyful {p}','{ph} नन्दिनी','{pn} नन्दिनी'),
('shakti','shakti','shakti','girl','power of {p}','{ph} शक्ति','{pn} शक्ति'),
('ambika','ambika','ambikaa','girl','nurturing {p}','{ph} अम्बिका','{pn} अम्बिका'),
('eshwari','eshwari','eeshvaree','girl','goddess of {p}','{ph} ईश्वरी','{pn} ईश्वरी'),
('vani','vani','vaaNee','girl','voice of {p}','{ph} वाणी','{pn} वाणी'),
('jyoti','jyoti','jyoti','girl','flame of {p}','{ph} ज्योति','{pn} ज्योति'),
]

# (prefix_key, suffix_key) pairs that are wrong or odd -> skip
BLOCKS = {
# feminine deity roots with masculine suffixes (except the well-known ones kept below)
('saraswati','dev'),('saraswati','nath'),('saraswati','prasad'),('saraswati','lal'),
('saraswati','kumar'),('saraswati','das'),('saraswati','dutt'),('saraswati','sharan'),
('saraswati','vallabh'),('saraswati','kanta'),('saraswati','swaroop'),('saraswati','murti'),
('saraswati','shankar'),('saraswati','bhakt'),('saraswati','sevak'),('saraswati','raj'),
('saraswati','chandra'),
('parvati','dev'),('parvati','nath'),('parvati','prasad'),('parvati','lal'),
('parvati','kumar'),('parvati','das'),('parvati','dutt'),('parvati','sharan'),
('parvati','vallabh'),('parvati','swaroop'),('parvati','murti'),
('parvati','shankar'),('parvati','bhakt'),('parvati','sevak'),('parvati','raj'),
('parvati','chandra'),('parvati','kanta'),
('gauri','dev'),('gauri','nath'),('gauri','prasad'),('gauri','lal'),
('gauri','kumar'),('gauri','das'),('gauri','dutt'),('gauri','sharan'),
('gauri','vallabh'),('gauri','kanta'),('gauri','swaroop'),('gauri','murti'),
('gauri','bhakt'),('gauri','sevak'),('gauri','raj'),('gauri','chandra'),
('durga','dev'),('durga','nath'),('durga','prasad'),('durga','lal'),
('durga','kumar'),('durga','das'),('durga','dutt'),('durga','sharan'),
('durga','vallabh'),('durga','kanta'),('durga','swaroop'),('durga','murti'),
('durga','shankar'),('durga','bhakt'),('durga','sevak'),('durga','raj'),
('durga','chandra'),
('kali','dev'),('kali','nath'),('kali','prasad'),('kali','lal'),
('kali','kumar'),('kali','das'),('kali','dutt'),('kali','sharan'),
('kali','vallabh'),('kali','kanta'),('kali','swaroop'),('kali','murti'),
('kali','shankar'),('kali','bhakt'),('kali','sevak'),('kali','raj'),
('kali','chandra'),
('sita','dev'),('sita','nath'),('sita','prasad'),('sita','lal'),
('sita','kumar'),('sita','das'),('sita','dutt'),('sita','sharan'),
('sita','vallabh'),('sita','swaroop'),('sita','murti'),
('sita','shankar'),('sita','bhakt'),('sita','sevak'),('sita','raj'),
('sita','chandra'),
('radha','dev'),('radha','nath'),('radha','prasad'),('radha','lal'),
('radha','kumar'),('radha','das'),('radha','dutt'),('radha','sharan'),
('radha','vallabh'),('radha','swaroop'),('radha','murti'),
('radha','shankar'),('radha','bhakt'),('radha','sevak'),('radha','raj'),
('radha','chandra'),
('lakshmi','prasad'),('lakshmi','lal'),('lakshmi','kumar'),('lakshmi','das'),
('lakshmi','dutt'),('lakshmi','sharan'),('lakshmi','swaroop'),('lakshmi','murti'),
('lakshmi','shankar'),('lakshmi','bhakt'),('lakshmi','sevak'),('lakshmi','raj'),
('lakshmi','chandra'),('lakshmi','vallabh'),
('uma','dev'),('uma','nath'),('uma','prasad'),('uma','lal'),
('uma','kumar'),('uma','das'),('uma','dutt'),('uma','sharan'),
('uma','vallabh'),('uma','kanta'),('uma','swaroop'),('uma','murti'),
('uma','bhakt'),('uma','sevak'),('uma','raj'),('uma','chandra'),
('ganga','dev'),('ganga','nath'),('ganga','lal'),
('ganga','kumar'),('ganga','dutt'),('ganga','sharan'),
('ganga','vallabh'),('ganga','kanta'),('ganga','swaroop'),('ganga','murti'),
('ganga','shankar'),('ganga','sevak'),('ganga','raj'),('ganga','chandra'),
('yamuna','dev'),('yamuna','nath'),('yamuna','lal'),
('yamuna','kumar'),('yamuna','dutt'),('yamuna','sharan'),
('yamuna','vallabh'),('yamuna','kanta'),('yamuna','swaroop'),('yamuna','murti'),
('yamuna','shankar'),('yamuna','sevak'),('yamuna','raj'),('yamuna','chandra'),
('narmada','dev'),('narmada','nath'),('narmada','prasad'),('narmada','lal'),
('narmada','kumar'),('narmada','das'),('narmada','dutt'),('narmada','sharan'),
('narmada','vallabh'),('narmada','kanta'),('narmada','swaroop'),('narmada','murti'),
('narmada','shankar'),('narmada','bhakt'),('narmada','sevak'),('narmada','raj'),
('narmada','chandra'),
('kaveri','dev'),('kaveri','nath'),('kaveri','prasad'),('kaveri','lal'),
('kaveri','kumar'),('kaveri','das'),('kaveri','dutt'),('kaveri','sharan'),
('kaveri','vallabh'),('kaveri','kanta'),('kaveri','swaroop'),('kaveri','murti'),
('kaveri','shankar'),('kaveri','bhakt'),('kaveri','sevak'),('kaveri','raj'),
('kaveri','chandra'),
# masculine deity roots with odd suffixes
('har','lal'),('har','kumar'),('har','chandra'),('har','dutt'),('har','raj'),
('har','murti'),('har','swaroop'),
('shiv','esh'),('shiv','kumar'),('shiv','chandra'),('shiv','raj'),('shiv','vallabh'),
('shiv','kanta'),
('ram','kanta'),('ram','vallabh'),('ram','murti'),('ram','swaroop'),
('krishn','esh'),('krishn','nath'),('krishn','kumar'),('krishn','chandra'),
('krishn','raj'),('krishn','vallabh'),('krishn','kanta'),('krishn','murti'),
('krishn','swaroop'),('krishn','shankar'),
('gopal','esh'),('gopal','nath'),('gopal','chandra'),('gopal','raj'),
('gopal','vallabh'),('gopal','kanta'),('gopal','murti'),('gopal','swaroop'),
('govind','esh'),('govind','chandra'),('govind','raj'),('govind','vallabh'),
('govind','kanta'),('govind','murti'),('govind','swaroop'),
('madhav','esh'),('madhav','nath'),('madhav','chandra'),('madhav','raj'),
('madhav','vallabh'),('madhav','kanta'),('madhav','murti'),('madhav','swaroop'),
('keshav','esh'),('keshav','chandra'),('keshav','raj'),('keshav','vallabh'),
('keshav','murti'),('keshav','swaroop'),
('narayan','esh'),('narayan','chandra'),('narayan','raj'),('narayan','vallabh'),
('narayan','kanta'),('narayan','murti'),('narayan','swaroop'),('narayan','lal'),
('dev','chandra'),('dev','murti'),('dev','swaroop'),
('sur','prasad'),('sur','lal'),('sur','kumar'),('sur','das'),('sur','bhakt'),
('sur','sevak'),('sur','sharan'),('sur','murti'),('sur','swaroop'),('sur','kanta'),
('ganesh','esh'),('ganesh','nath'),('ganesh','chandra'),('ganesh','raj'),
('ganesh','vallabh'),('ganesh','kanta'),('ganesh','murti'),('ganesh','swaroop'),
('surya','esh'),('surya','nath'),('surya','kumar'),('surya','chandra'),
('surya','raj'),('surya','vallabh'),('surya','kanta'),('surya','murti'),
('surya','swaroop'),('surya','shankar'),('surya','dutt'),
('indra','esh'),('indra','prasad'),('indra','lal'),('indra','das'),
('indra','sharan'),('indra','murti'),('indra','swaroop'),('indra','kanta'),
('agni','esh'),('agni','prasad'),('agni','lal'),('agni','das'),
('agni','sharan'),('agni','murti'),('agni','swaroop'),('agni','kanta'),
('vayu','esh'),('vayu','prasad'),('vayu','lal'),('vayu','das'),
('vayu','sharan'),('vayu','murti'),('vayu','swaroop'),('vayu','kanta'),
('varun','esh'),('varun','prasad'),('varun','lal'),('varun','das'),
('varun','sharan'),('varun','murti'),('varun','swaroop'),('varun','kanta'),
('kuber','esh'),('kuber','prasad'),('kuber','lal'),('kuber','das'),
('kuber','sharan'),('kuber','murti'),('kuber','swaroop'),('kuber','kanta'),
('hanuman','esh'),('hanuman','nath'),('hanuman','chandra'),('hanuman','raj'),
('hanuman','vallabh'),('hanuman','kanta'),('hanuman','murti'),('hanuman','swaroop'),
# odd virtue/nature combos
('su','nath'),('su','prasad'),('su','lal'),('su','kumar'),('su','das'),
('su','dutt'),('su','sharan'),('su','bhakt'),('su','sevak'),('su','shankar'),
('su','vallabh'),('su','kanta'),('su','swaroop'),('su','murti'),('su','raj'),
('su','chandra'),
('su','esh'),
('maha','priya'),('maha','maya'),('maha','devi'),('maha','vati'),
('maha','rani'),('maha','kumari'),('maha','dasi'),('maha','mala'),
('maha','lata'),('maha','bala'),('maha','shri'),('maha','dulari'),
('raj','priya'),('raj','maya'),('raj','devi'),('raj','vati'),('raj','dasi'),
('raj','mala'),('raj','lata'),('raj','bala'),('raj','shri'),('raj','dulari'),
('amar','maya'),('amar','mala'),('amar','lata'),('amar','bala'),('amar','dulari'),
('ajay','maya'),('ajay','mala'),('ajay','lata'),('ajay','bala'),('ajay','dulari'),
('abhay','maya'),('abhay','mala'),('abhay','lata'),('abhay','bala'),('abhay','dulari'),
('vijay','maya'),('vijay','lata'),('vijay','bala'),('vijay','dulari'),
('jai','maya'),('jai','lata'),('jai','bala'),('jai','dulari'),('jai','shri'),
('dharam','priya'),('dharam','maya'),('dharam','devi'),('dharam','vati'),
('dharam','rani'),('dharam','kumari'),('dharam','dasi'),('dharam','mala'),
('dharam','lata'),('dharam','bala'),('dharam','shri'),('dharam','dulari'),
('karam','priya'),('karam','maya'),('karam','devi'),('karam','vati'),
('karam','rani'),('karam','kumari'),('karam','dasi'),('karam','mala'),
('karam','lata'),('karam','bala'),('karam','shri'),('karam','dulari'),
('bal','priya'),('bal','maya'),('bal','devi'),('bal','vati'),
('bal','rani'),('bal','kumari'),('bal','dasi'),('bal','mala'),
('bal','lata'),('bal','bala'),('bal','shri'),('bal','dulari'),
('tej','devi'),('tej','rani'),('tej','kumari'),('tej','dasi'),('tej','dulari'),
('yash','devi'),('yash','rani'),('yash','kumari'),('yash','dasi'),('yash','dulari'),
('yash','mala'),('yash','lata'),('yash','bala'),
('dhan','lata'),('dhan','bala'),('dhan','dulari'),
('vir','priya'),('vir','maya'),('vir','devi'),('vir','vati'),
('vir','rani'),('vir','kumari'),('vir','dasi'),('vir','mala'),
('vir','lata'),('vir','bala'),('vir','shri'),('vir','dulari'),
('sohan','priya'),('sohan','maya'),('sohan','devi'),('sohan','vati'),
('sohan','rani'),('sohan','kumari'),('sohan','dasi'),('sohan','mala'),
('sohan','lata'),('sohan','bala'),('sohan','shri'),('sohan','dulari'),
('kishan','priya'),('kishan','maya'),('kishan','devi'),('kishan','vati'),
('kishan','rani'),('kishan','kumari'),('kishan','dasi'),('kishan','mala'),
('kishan','lata'),('kishan','bala'),('kishan','shri'),('kishan','dulari'),
('sundar','maya'),('sundar','mala'),('sundar','lata'),('sundar','bala'),
('sundar','dulari'),('sundar','shri'),
('guru','priya'),('guru','maya'),('guru','devi'),('guru','vati'),
('guru','rani'),('guru','kumari'),('guru','dasi'),('guru','mala'),
('guru','lata'),('guru','bala'),('guru','shri'),('guru','dulari'),
('mohan','maya'),('mohan','mala'),('mohan','lata'),('mohan','bala'),
('mohan','shri'),('mohan','dulari'),
('madan','maya'),('madan','mala'),('madan','lata'),('madan','bala'),
('madan','shri'),('madan','dulari'),('madan','devi'),('madan','rani'),
('pankaj','priya'),('pankaj','maya'),('pankaj','devi'),('pankaj','vati'),
('pankaj','rani'),('pankaj','kumari'),('pankaj','dasi'),('pankaj','mala'),
('pankaj','lata'),('pankaj','bala'),('pankaj','shri'),('pankaj','dulari'),
('jalaj','priya'),('jalaj','maya'),('jalaj','devi'),('jalaj','vati'),
('jalaj','rani'),('jalaj','kumari'),('jalaj','dasi'),('jalaj','mala'),
('jalaj','lata'),('jalaj','bala'),('jalaj','shri'),('jalaj','dulari'),
('aravind','priya'),('aravind','maya'),('aravind','devi'),('aravind','vati'),
('aravind','rani'),('aravind','kumari'),('aravind','dasi'),('aravind','mala'),
('aravind','lata'),('aravind','bala'),('aravind','shri'),('aravind','dulari'),
('rajiv','priya'),('rajiv','maya'),('rajiv','devi'),('rajiv','vati'),
('rajiv','rani'),('rajiv','kumari'),('rajiv','dasi'),('rajiv','mala'),
('rajiv','lata'),('rajiv','bala'),('rajiv','shri'),('rajiv','dulari'),
('mayur','priya'),('mayur','maya'),('mayur','devi'),('mayur','vati'),
('mayur','rani'),('mayur','kumari'),('mayur','dasi'),('mayur','mala'),
('mayur','lata'),('mayur','bala'),('mayur','shri'),('mayur','dulari'),
('garud','priya'),('garud','maya'),('garud','devi'),('garud','vati'),
('garud','rani'),('garud','kumari'),('garud','dasi'),('garud','mala'),
('garud','lata'),('garud','bala'),('garud','shri'),('garud','dulari'),
('shuk','priya'),('shuk','maya'),('shuk','devi'),('shuk','vati'),
('shuk','rani'),('shuk','kumari'),('shuk','dasi'),('shuk','mala'),
('shuk','lata'),('shuk','bala'),('shuk','shri'),('shuk','dulari'),
('chatak','priya'),('chatak','maya'),('chatak','devi'),('chatak','vati'),
('chatak','rani'),('chatak','kumari'),('chatak','dasi'),('chatak','mala'),
('chatak','lata'),('chatak','bala'),('chatak','shri'),('chatak','dulari'),
('bulbul','dev'),('bulbul','nath'),('bulbul','esh'),('bulbul','prasad'),
('bulbul','lal'),('bulbul','kumar'),('bulbul','chandra'),('bulbul','dutt'),
('bulbul','das'),('bulbul','sharan'),('bulbul','vallabh'),('bulbul','kanta'),
('bulbul','swaroop'),('bulbul','murti'),('bulbul','shankar'),('bulbul','bhakt'),
('bulbul','sevak'),('bulbul','raj'),
# feminine-only roots with odd girl suffixes
('mallika','vati'),('mallika','bala'),('mallika','shri'),('mallika','kumari'),
('juhi','vati'),('juhi','bala'),('juhi','shri'),('juhi','kumari'),('juhi','rani'),
('chameli','vati'),('chameli','bala'),('chameli','shri'),('chameli','kumari'),
('chameli','rani'),
('varsha','vati'),('varsha','bala'),('varsha','shri'),
('chandni','vati'),('chandni','bala'),('chandni','kumari'),
('roshni','vati'),('roshni','bala'),('roshni','kumari'),
('khushi','vati'),('khushi','bala'),('khushi','shri'),
('muskan','vati'),('muskan','bala'),('muskan','shri'),
('aarti','vati'),('aarti','bala'),('aarti','kumari'),
('puja','vati'),('puja','bala'),('puja','kumari'),
('archana','vati'),('archana','bala'),('archana','shri'),
('vandana','vati'),('vandana','bala'),('vandana','shri'),
('sadhana','vati'),('sadhana','bala'),('sadhana','shri'),
('bhakti','vati'),('bhakti','bala'),('bhakti','kumari'),
('shraddha','vati'),('shraddha','bala'),('shraddha','shri'),
('shobha','vati'),('shobha','bala'),('shobha','shri'),
('naina','vati'),('naina','bala'),('naina','kumari'),
('kajal','vati'),('kajal','bala'),('kajal','kumari'),
('payal','vati'),('payal','bala'),('payal','kumari'),
('nalini','vati'),('nalini','bala'),('nalini','kumari'),
('kumudini','vati'),('kumudini','bala'),('kumudini','kumari'),
('rakaa','vati'),('rakaa','bala'),('rakaa','kumari'),
('hema','vati'),('hema','bala'),('hema','kumari'),
('hanuman','pati'),
('hanuman','pal'),
('hanuman','veer'),
('hanuman','jit'),
('hanuman','prakash'),
('hanuman','anand'),
('hanuman','nandan'),
('hanuman','charan'),
('hanuman','ashish'),
('hanuman','kishore'),
('hanuman','lochan'),
('hanuman','prabha'),
('hanuman','kanti'),
('ganesh','pati'),
('ganesh','pal'),
('ganesh','veer'),
('ganesh','jit'),
('ganesh','prakash'),
('ganesh','anand'),
('ganesh','nandan'),
('ganesh','charan'),
('ganesh','ashish'),
('ganesh','kishore'),
('ganesh','lochan'),
('ganesh','prabha'),
('ganesh','kanti'),
('har','pati'),
('har','pal'),
('har','veer'),
('har','jit'),
('shiv','pati'),
('shiv','pal'),
('shiv','veer'),
('shiv','jit'),
('ram','pati'),
('ram','pal'),
('ram','veer'),
('ram','jit'),
('krishn','pati'),
('krishn','pal'),
('krishn','veer'),
('krishn','jit'),
('gopal','pati'),
('gopal','pal'),
('gopal','veer'),
('gopal','jit'),
('govind','pati'),
('govind','pal'),
('govind','veer'),
('govind','jit'),
('madhav','pati'),
('madhav','pal'),
('madhav','veer'),
('madhav','jit'),
('keshav','pati'),
('keshav','pal'),
('keshav','veer'),
('keshav','jit'),
('narayan','pati'),
('narayan','pal'),
('narayan','veer'),
('narayan','jit'),
('dev','pati'),
('dev','pal'),
('dev','veer'),
('dev','jit'),
('sur','pati'),
('sur','pal'),
('sur','veer'),
('sur','jit'),
('surya','pati'),
('surya','pal'),
('surya','veer'),
('surya','jit'),
('indra','pati'),
('indra','pal'),
('indra','veer'),
('indra','jit'),
('agni','pati'),
('agni','pal'),
('agni','veer'),
('agni','jit'),
('vayu','pati'),
('vayu','pal'),
('vayu','veer'),
('vayu','jit'),
('varun','pati'),
('varun','pal'),
('varun','veer'),
('varun','jit'),
('kuber','pati'),
('kuber','pal'),
('kuber','veer'),
('kuber','jit'),
('mohan','pati'),
('mohan','pal'),
('mohan','veer'),
('mohan','jit'),
('madan','pati'),
('madan','pal'),
('madan','veer'),
('madan','jit'),
('sohan','pati'),
('sohan','pal'),
('sohan','veer'),
('sohan','jit'),
('kishan','pati'),
('kishan','pal'),
('kishan','veer'),
('kishan','jit'),
('sundar','pati'),
('sundar','pal'),
('sundar','veer'),
('sundar','jit'),
('guru','pati'),
('guru','pal'),
('guru','veer'),
('guru','jit'),
('achyut','pati'),
('achyut','pal'),
('achyut','veer'),
('achyut','jit'),
('anant','pati'),
('anant','pal'),
('anant','veer'),
('anant','jit'),
('damodar','pati'),
('damodar','pal'),
('damodar','veer'),
('damodar','jit'),
('janardan','pati'),
('janardan','pal'),
('janardan','veer'),
('janardan','jit'),
('murari','pati'),
('murari','pal'),
('murari','veer'),
('murari','jit'),
('mukund','pati'),
('mukund','pal'),
('mukund','veer'),
('mukund','jit'),
('shankar','pati'),
('shankar','pal'),
('shankar','veer'),
('shankar','jit'),
('mahadev','pati'),
('mahadev','pal'),
('mahadev','veer'),
('mahadev','jit'),
('neelkanth','pati'),
('neelkanth','pal'),
('neelkanth','veer'),
('neelkanth','jit'),
('trilochan','pati'),
('trilochan','pal'),
('trilochan','veer'),
('trilochan','jit'),
('pashupati','pati'),
('pashupati','pal'),
('pashupati','veer'),
('pashupati','jit'),
('sudarshan','pati'),
('sudarshan','pal'),
('sudarshan','veer'),
('sudarshan','jit'),
('vaikunth','pati'),
('vaikunth','pal'),
('vaikunth','veer'),
('vaikunth','jit'),
('srinivas','pati'),
('srinivas','pal'),
('srinivas','veer'),
('srinivas','jit'),
('balram','pati'),
('balram','pal'),
('balram','veer'),
('balram','jit'),
('parshuram','pati'),
('parshuram','pal'),
('parshuram','veer'),
('parshuram','jit'),
('raghav','pati'),
('raghav','pal'),
('raghav','veer'),
('raghav','jit'),
('kartik','pati'),
('kartik','pal'),
('kartik','veer'),
('kartik','jit'),
('skand','pati'),
('skand','pal'),
('skand','veer'),
('skand','jit'),
('maruti','pati'),
('maruti','pal'),
('maruti','veer'),
('maruti','jit'),
('pavan','pati'),
('pavan','pal'),
('pavan','veer'),
('pavan','jit'),
('anil','pati'),
('anil','pal'),
('anil','veer'),
('anil','jit'),
('mayur','pati'),
('mayur','pal'),
('mayur','veer'),
('mayur','jit'),
('mayur','prakash'),
('mayur','anand'),
('mayur','nandan'),
('mayur','charan'),
('mayur','ashish'),
('mayur','kishore'),
('mayur','lochan'),
('mayur','prabha'),
('mayur','kanti'),
('garud','pati'),
('garud','pal'),
('garud','veer'),
('garud','jit'),
('garud','prakash'),
('garud','anand'),
('garud','nandan'),
('garud','charan'),
('garud','ashish'),
('garud','kishore'),
('garud','lochan'),
('garud','prabha'),
('garud','kanti'),
('shuk','pati'),
('shuk','pal'),
('shuk','veer'),
('shuk','jit'),
('shuk','prakash'),
('shuk','anand'),
('shuk','nandan'),
('shuk','charan'),
('shuk','ashish'),
('shuk','kishore'),
('shuk','lochan'),
('shuk','prabha'),
('shuk','kanti'),
('chatak','pati'),
('chatak','pal'),
('chatak','veer'),
('chatak','jit'),
('chatak','prakash'),
('chatak','anand'),
('chatak','nandan'),
('chatak','charan'),
('chatak','ashish'),
('chatak','kishore'),
('chatak','lochan'),
('chatak','prabha'),
('chatak','kanti'),
('pankaj','pati'),
('pankaj','pal'),
('pankaj','veer'),
('pankaj','jit'),
('pankaj','prakash'),
('pankaj','anand'),
('pankaj','nandan'),
('pankaj','charan'),
('pankaj','ashish'),
('pankaj','kishore'),
('pankaj','lochan'),
('pankaj','prabha'),
('pankaj','kanti'),
('jalaj','pati'),
('jalaj','pal'),
('jalaj','veer'),
('jalaj','jit'),
('jalaj','prakash'),
('jalaj','anand'),
('jalaj','nandan'),
('jalaj','charan'),
('jalaj','ashish'),
('jalaj','kishore'),
('jalaj','lochan'),
('jalaj','prabha'),
('jalaj','kanti'),
('aravind','pati'),
('aravind','pal'),
('aravind','veer'),
('aravind','jit'),
('aravind','prakash'),
('aravind','anand'),
('aravind','nandan'),
('aravind','charan'),
('aravind','ashish'),
('aravind','kishore'),
('aravind','lochan'),
('aravind','prabha'),
('aravind','kanti'),
('rajiv','pati'),
('rajiv','pal'),
('rajiv','veer'),
('rajiv','jit'),
('rajiv','prakash'),
('rajiv','anand'),
('rajiv','nandan'),
('rajiv','charan'),
('rajiv','ashish'),
('rajiv','kishore'),
('rajiv','lochan'),
('rajiv','prabha'),
('rajiv','kanti'),
('su','pati'),
('su','pal'),
('su','veer'),
('su','jit'),
('su','prakash'),
('su','anand'),
('su','nandan'),
('su','charan'),
('su','ashish'),
('su','kishore'),
('su','lochan'),
('su','prabha'),
('su','kanti'),
('shankar','shankar'),
('vir','veer'),
('ajay','jit'),
('vijay','jit'),
('abhay','jit'),
('aanand','anand'),
('jyoti','prabha'),
('srinivas','esh'),
('pashupati','esh'),
('murari','esh'),
('su','shakti'),
('su','ambika'),
('su','eshwari'),
('su','vani'),
('su','jyoti'),
('mayur','nandini'),
('mayur','shakti'),
('mayur','ambika'),
('mayur','eshwari'),
('mayur','vani'),
('mayur','jyoti'),
('garud','nandini'),
('garud','shakti'),
('garud','ambika'),
('garud','eshwari'),
('garud','vani'),
('garud','jyoti'),
('shuk','nandini'),
('shuk','shakti'),
('shuk','ambika'),
('shuk','eshwari'),
('shuk','vani'),
('shuk','jyoti'),
('chatak','nandini'),
('chatak','shakti'),
('chatak','ambika'),
('chatak','eshwari'),
('chatak','vani'),
('chatak','jyoti'),
('pankaj','nandini'),
('pankaj','shakti'),
('pankaj','ambika'),
('pankaj','eshwari'),
('pankaj','vani'),
('pankaj','jyoti'),
('jalaj','nandini'),
('jalaj','shakti'),
('jalaj','ambika'),
('jalaj','eshwari'),
('jalaj','vani'),
('jalaj','jyoti'),
('aravind','nandini'),
('aravind','shakti'),
('aravind','ambika'),
('aravind','eshwari'),
('aravind','vani'),
('aravind','jyoti'),
('rajiv','nandini'),
('rajiv','shakti'),
('rajiv','ambika'),
('rajiv','eshwari'),
('rajiv','vani'),
('rajiv','jyoti'),
('jyoti','jyoti'),
}

# (prefix_key, suffix_key) -> (display_override, tr_override)
OVERRIDES = {
('har','nath'): ('Harinath','harinaath'),
('har','esh'): ('Haresh','haresh'),
('har','priya'): ('Haripriya','haripriyaa'),
('har','devi'): ('Haridevi','haridevee'),
('har','dasi'): ('Haridasi','haridaasee'),
('har','maya'): ('Harimaya','harimaayaa'),
('har','mala'): ('Harimala','harimaalaa'),
('har','dulari'): ('Haridulari','haridulaaree'),
('har','kumari'): ('Harikumari','harikumaaree'),
('har','rani'): ('Harirani','hariraanee'),
('har','lata'): ('Harilata','harilataa'),
('har','bala'): ('Haribala','haribaalaa'),
('har','shri'): ('Harishri','harishree'),
('har','vati'): ('Harivati','harivatee'),
('krishn','das'): ('Krishnadas','kRShNadaas'),
('krishn','dasi'): ('Krishnadasi','kRShNadaasee'),
('krishn','devi'): ('Krishnadevi','kRShNadevee'),
('krishn','priya'): ('Krishnapriya','kRShNapriyaa'),
('krishn','maya'): ('Krishnamaya','kRShNamaayaa'),
('krishn','mala'): ('Krishnamala','kRShNamaalaa'),
('jai','dev'): ('Jaidev','jayadev'),
('jai','mala'): ('Jaimala','jayamaalaa'),
('jai','priya'): ('Jaipriya','jayapriyaa'),
('jai','devi'): ('Jaidevi','jayadevee'),
('jai','rani'): ('Jairani','jayaraanee'),
('jai','kumar'): ('Jaikumar','jayakumaar'),
('jai','dasi'): ('Jaidasi','jayadaasee'),
('ram','esh'): ('Ramesh','ramesh'),
('maha','esh'): ('Mahesh','mahesh'),
('uma','esh'): ('Umesh','umesh'),
('rakaa','esh'): ('Rakesh','raakesh'),
('raj','esh'): ('Rajesh','raajesh'),
('dev','esh'): ('Devesh','devesh'),
('sur','esh'): ('Suresh','suresh'),
('nar','esh'): ('Naresh','naresh'),
('din','esh'): ('Dinesh','dinesh'),
('yog','esh'): ('Yogesh','yogesh'),
('hit','esh'): ('Hitesh','hitesh'),
('sarv','esh'): ('Sarvesh','sarvesh'),
('akhil','esh'): ('Akhilesh','akhilesh'),
('nikhil','esh'): ('Nikhilesh','nikhilesh'),
('som','esh'): ('Somesh','somesh'),
('shail','esh'): ('Shailesh','shailesh'),
('neel','esh'): ('Neelesh','neelesh'),
('dhan','esh'): ('Dhanesh','dhanesh'),
('gyan','esh'): ('Gyanesh','gyaanesh'),
('kaam','esh'): ('Kamesh','kaamesh'),
('vyom','esh'): ('Vyomesh','vyomesh'),
('bhuvan','esh'): ('Bhuvnesh','bhuvanesh'),
('kamal','esh'): ('Kamalesh','kamalesh'),
('vimal','esh'): ('Vimalesh','vimalesh'),
('shiv','esh'): ('Shivesh','shivesh'),
}
