# Curated modern Indian baby names (hand-verified, attested usage).
# Format: (latin, devanagari, gender, english_meaning)
SEEDS3 = [
# ---- modern boy names ----
('Aarav','आरव','boy','peaceful sound'),
('Vihaan','विहान','boy','dawn'),
('Vivaan','विवान','boy','full of life'),
('Reyansh','रेयांश','boy','ray of light'),
('Ayaan','अयान','boy','gift of God'),
('Kabir','कबीर','boy','the great'),
('Arnav','अर्णव','boy','ocean'),
('Advaith','अद्वैत','boy','non-dual'),
('Atharv','अथर्व','boy','the Atharva Veda'),
('Dhruv','ध्रुव','boy','the pole star'),
('Ishaan','ईशान','boy','guardian of the northeast'),
('Kiaan','कियान','boy','grace of God'),
('Pranav','प्रणव','boy','the sacred syllable Om'),
('Shaurya','शौर्य','boy','valor'),
('Advik','अद्विक','boy','unique'),
('Hridaan','हृदान','boy','kind-hearted'),
('Darsh','दर्श','boy','vision'),
('Daksh','दक्ष','boy','skilled'),
('Ekansh','एकांश','boy','entire'),
('Gaurav','गौरव','boy','pride'),
('Hardik','हार्दिक','boy','heartfelt'),
('Lakshya','लक्ष्य','boy','aim'),
('Manav','मानव','boy','human'),
('Omkar','ओंकार','boy','the syllable Om'),
('Ranveer','रणवीर','boy','heroic in battle'),
('Samarth','समर्थ','boy','capable'),
('Tanmay','तन्मय','boy','absorbed'),
('Utkarsh','उत्कर्ष','boy','progress'),
('Vedant','वेदान्त','boy','the Upanishads'),
('Yug','युग','boy','era'),
('Aarush','आरुष','boy','first ray of the sun'),
('Ahaan','अहान','boy','dawn'),
('Ansh','अंश','boy','portion'),
('Devansh','देवांश','boy','portion of God'),
('Rudransh','रुद्रांश','boy','portion of Shiva'),
('Shivansh','शिवांश','boy','portion of Shiva'),
('Nirvaan','निर्वाण','boy','liberation'),
('Yashvardhan','यशवर्धन','boy','increasing glory'),
('Aaryan','आर्यन','boy','noble'),
('Eshan','ईशान','boy','the sun'),
('Gatik','गतिक','boy','progressing'),
('Hemant','हेमन्त','boy','winter'),
('Jatin','जतिन','boy','ascetic'),
('Kanav','कणव','boy','intelligent'),
('Luv','लव','boy','son of Rama'),
('Naman','नमन','boy','salutation'),
('Ojas','ओजस','boy','vigor'),
('Parv','पर्व','boy','festival'),
('Rachit','रचित','boy','created'),
('Taksh','तक्ष','boy','craftsman'),
('Ujjwal','उज्ज्वल','boy','bright'),
('Vansh','वंश','boy','lineage'),
('Waman','वामन','boy','Vishnu the dwarf'),
('Yatharth','यथार्थ','boy','reality'),
('Abhay','अभय','boy','fearless'),
('Ajay','अजय','boy','unconquered'),
('Vijay','विजय','boy','victory'),
('Sanjay','संजय','boy','victorious'),
('Dhananjay','धनंजय','boy','Arjuna'),
('Mrityunjay','मृत्युंजय','boy','conqueror of death'),
('Chinmay','चिन्मय','boy','full of consciousness'),
('Shrinivas','श्रीनिवास','boy','Vishnu'),
('Hariom','हरिओम','boy','Vishnu and Om'),
('Yashwant','यशवन्त','boy','glorious'),
('Balwant','बलवन्त','boy','strong'),
('Bhagwant','भगवन्त','boy','fortunate'),
('Kuldeep','कुलदीप','boy','lamp of the family'),
('Navdeep','नवदीप','boy','new lamp'),
('Param','परम','boy','supreme'),
('Varun','वरुण','boy','lord of waters'),
('Arun','अरुण','boy','dawn'),
('Tarun','तरुण','boy','young'),
('Karun','करुण','boy','compassionate'),
('Anmol','अनमोल','boy','priceless'),
('Atul','अतुल','boy','peerless'),
('Vipul','विपुल','boy','abundant'),
('Komal','कोमल','boy','gentle'),
('Nirmal','निर्मल','boy','pure'),
('Vimal','विमल','boy','pure'),
('Prakhar','प्रखर','boy','intense'),
('Prateek','प्रतीक','boy','symbol'),
('Sanket','संकेत','boy','sign'),
('Sarthak','सार्थक','boy','meaningful'),
('Suvrat','सुव्रत','boy','devout'),
('Vrat','व्रत','boy','vow'),
('Yatin','यतिन','boy','ascetic'),
('Tapas','तपस','boy','austerity'),
('Shreyas','श्रेयस','boy','auspicious'),
('Siddharth','सिद्धार्थ','boy','the Buddha'),
('Gautam','गौतम','boy','the Buddha'),
('Mahavir','महावीर','boy','the great hero'),
('Vardhaman','वर्धमान','boy','Mahavira'),
('Rishabh','ऋषभ','boy','the first Tirthankara'),
('Neminath','नेमिनाथ','boy','a Tirthankara'),
('Parshwanath','पार्श्वनाथ','boy','a Tirthankara'),
('Adinath','आदिनाथ','boy','the first lord'),
('Shantanu','शान्तनु','boy','wholesome'),
('Devvrat','देवव्रत','boy','Bhishma'),
('Yudhishthir','युधिष्ठिर','boy','eldest Pandava'),
('Sahadev','सहदेव','boy','youngest Pandava'),
# ---- modern girl names ----
('Aadhya','आध्या','girl','the first power'),
('Ananya','अनन्या','girl','matchless'),
('Diya','दिया','girl','lamp'),
('Myra','मायरा','girl','extraordinary'),
('Navya','नव्या','girl','new'),
('Ira','ईरा','girl','earth'),
('Saanvi','सान्वी','girl','Lakshmi'),
('Aanya','आन्या','girl','gracious'),
('Anika','अनिका','girl','graceful'),
('Kiara','कियारा','girl','bright'),
('Shanaya','शनाया','girl','distinguished'),
('Avni','अवनि','girl','earth'),
('Riya','रिया','girl','singer'),
('Siya','सिया','girl','Sita'),
('Vanya','वन्या','girl','of the forest'),
('Inaaya','इनाया','girl','gift of God'),
('Yashvi','यश्वी','girl','glorious'),
('Tejasvi','तेजस्वी','girl','radiant'),
('Manvi','मानवी','girl','human'),
('Tanvi','तन्वी','girl','delicate'),
('Urvi','उर्वी','girl','earth'),
('Bhuvi','भुवी','girl','earth'),
('Shreya','श्रेया','girl','beautiful'),
('Shravya','श्रव्या','girl','worth hearing'),
('Mahi','माही','girl','the earth'),
('Ruhi','रूही','girl','soul'),
('Dhwani','ध्वनि','girl','sound'),
('Anvi','अन्वी','girl','goddess of the forest'),
('Prisha','प्रीशा','girl','beloved'),
('Aarohi','आरोही','girl','musical ascent'),
('Svara','स्वरा','girl','musical note'),
('Taanvi','तान्वी','girl','delicate'),
('Ishita','इशिता','girl','desired'),
('Esha','एषा','girl','desire'),
('Trisha','तृषा','girl','thirst'),
('Nisha','निशा','girl','night'),
('Asha','आशा','girl','hope'),
('Usha','उषा','girl','dawn'),
('Sandhya','संध्या','girl','twilight'),
('Ritu','ऋतु','girl','season'),
('Vasanti','वासन्ती','girl','of spring'),
('Sharada','शारदा','girl','Saraswati'),
('Vagdevi','वाग्देवी','girl','goddess of speech'),
('Bharati','भारती','girl','Saraswati'),
('Medha','मेधा','girl','intellect'),
('Pragya','प्रज्ञा','girl','wisdom'),
('Smriti','स्मृति','girl','memory'),
('Shruti','श्रुति','girl','the Vedas'),
('Richa','ऋचा','girl','hymn'),
('Stuti','स्तुति','girl','praise'),
('Vandana','वन्दना','girl','worship'),
('Archana','अर्चना','girl','worship'),
('Aradhana','आराधना','girl','worship'),
('Upasana','उपासना','girl','devotion'),
('Sadhana','साधना','girl','spiritual practice'),
('Tapasya','तपस्या','girl','austerity'),
('Karuna','करुणा','girl','compassion'),
('Maitri','मैत्री','girl','friendship'),
('Shanti','शान्ति','girl','peace'),
('Kshama','क्षमा','girl','forgiveness'),
('Daya','दया','girl','kindness'),
('Seva','सेवा','girl','service'),
('Bhakti','भक्ति','girl','devotion'),
('Shraddha','श्रद्धा','girl','faith'),
('Aastha','आस्था','girl','faith'),
('Nishtha','निष्ठा','girl','dedication'),
('Pratibha','प्रतिभा','girl','talent'),
('Manisha','मनीषा','girl','wisdom'),
('Garima','गरिमा','girl','dignity'),
('Mahima','महिमा','girl','glory'),
('Lalima','ललिमा','girl','beauty'),
('Nilima','नीलिमा','girl','blueness'),
('Arunima','अरुणिमा','girl','dawn glow'),
('Pratima','प्रतिमा','girl','idol'),
('Anupama','अनुपमा','girl','incomparable'),
('Uttama','उत्तमा','girl','excellent'),
('Kanishka','कनिष्का','girl','small'),
('Tanishka','तनिष्का','girl','jewel'),
('Anushka','अनुष्का','girl','grace'),
('Priyanka','प्रियंका','girl','beloved'),
('Deepika','दीपिका','girl','lamp'),
('Mallika','मल्लिका','girl','jasmine'),
('Chandrika','चन्द्रिका','girl','moonlight'),
('Kumudini','कुमुदिनी','girl','lotus pond'),
('Nalini','नलिनी','girl','lotus'),
('Padmini','पद्मिनी','girl','lotus'),
('Rajani','रजनी','girl','night'),
('Yamini','यामिनी','girl','night'),
('Shalini','शालिनी','girl','modest'),
('Malini','मालिनी','girl','garlanded'),
('Ragini','रागिनी','girl','melody'),
('Yogini','योगिनी','girl','ascetic woman'),
('Gayatri','गायत्री','girl','the Gayatri mantra'),
('Savitri','सावित्री','girl','the sun goddess'),
('Damayanti','दमयन्ती','girl',"Nala's queen"),
('Shakuntala','शकुन्तला','girl',"Kalidasa's heroine"),
('Vasavadatta','वासवदत्ता','girl','classical heroine'),
('Kadambari','कादम्बरी','girl',"Banabhatta's heroine"),
('Purnima','पूर्णिमा','girl','full moon'),
('Amavasya','अमावस्या','girl','new moon'),
('Ekadashi','एकादशी','girl','eleventh lunar day'),
('Navami','नवमी','girl','ninth lunar day'),
('Ashtami','अष्टमी','girl','eighth lunar day'),
('Saptami','सप्तमी','girl','seventh lunar day'),
('Shashthi','षष्ठी','girl','sixth lunar day'),
('Panchami','पंचमी','girl','fifth lunar day'),
('Chaturthi','चतुर्थी','girl','fourth lunar day'),
('Tritiya','तृतीया','girl','third lunar day'),
('Dwitiya','द्वितीया','girl','second lunar day'),
('Pratipada','प्रतिपदा','girl','first lunar day'),
('Rashi','राशि','girl','zodiac sign'),
# ---- unisex ----
('Aman','अमन','both','peace'),
('Amar','अमर','both','immortal'),
('Kiran','किरण','both','ray of light'),
('Jyoti','ज्योति','both','flame'),
('Prakash','प्रकाश','both','light'),
('Anand','आनन्द','both','bliss'),
('Prem','प्रेम','both','love'),
('Sneha','स्नेह','both','affection'),
('Milan','मिलन','both','union'),
('Sangam','संगम','both','confluence'),
('Uday','उदय','both','sunrise'),
('Aakash','आकाश','both','sky'),
('Sagar','सागर','both','ocean'),
('Niranjan','निरंजन','both','spotless'),
('Nirav','नीरव','both','quiet'),
('Shubham','शुभम','both','auspicious'),
('Dev','देव','both','divine'),
]
