# Hand-curated seed names: deities. Format: (latin, devanagari, gender, english meaning)
SEEDS1 = [
("Aarav","आरव","boy","peaceful sound"),
("Achyut","अच्युत","boy","infallible Vishnu"),
("Anant","अनन्त","boy","the endless"),
("Damodar","दामोदर","boy","rope-bellied Krishna"),
("Gopal","गोपाल","boy","cowherd Krishna"),
("Govind","गोविन्द","boy","finder of cows"),
("Hari","हरि","boy","remover of sorrow"),
("Janardan","जनार्दन","boy","protector of people"),
("Keshav","केशव","boy","long-haired Vishnu"),
("Madhav","माधव","boy","lord of spring"),
("Mohan","मोहन","boy","the enchanter"),
("Mukund","मुकुन्द","boy","giver of liberation"),
("Murari","मुरारि","boy","foe of Mura"),
("Narayan","नारायण","boy","refuge of all"),
("Nandlal","नन्दलाल","boy","beloved son of Nanda"),
("Banke","बाँके","boy","the charming Krishna"),
("Bihari","बिहारी","boy","the divine enjoyer"),
("Madan","मदन","boy","god of love"),
("Manohar","मनोहर","boy","heart-stealing"),
("Chitchor","चितचोर","boy","stealer of hearts"),
("Ranchod","रणछोड़","boy","who left the battlefield"),
("Dwarkadhish","द्वारकाधीश","boy","lord of Dwarka"),
("Yadunandan","यदुनंदन","boy","joy of the Yadus"),
("Devkinandan","देवकीनंदन","boy","son of Devaki"),
("Yashodanandan","यशोदानंदन","boy","son of Yashoda"),
("Nandkishore","नन्दकिशोर","boy","young son of Nanda"),
("Ghanshyam","घनश्याम","boy","dark as raincloud"),
("Shyamsundar","श्यामसुंदर","boy","beautiful dark Krishna"),
("Pitambar","पीताम्बर","boy","wearing yellow robes"),
("Vanmali","वनमाली","boy","garlanded with forest flowers"),
("Giridhari","गिरिधारी","boy","lifter of Govardhan"),
("Murlidhar","मुरलीधर","boy","flute bearer"),
("Venugopal","वेणुगोपाल","boy","flute-playing cowherd"),
("Parthasarathi","पार्थसारथि","boy","Arjuna's charioteer"),
("Yogeshwar","योगेश्वर","boy","lord of yoga"),
("Jagannath","जगन्नाथ","boy","lord of the universe"),
("Vasudev","वासुदेव","boy","son of Vasudeva"),
("Trivikram","त्रिविक्रम","boy","three strides"),
("Vaman","वामन","boy","dwarf incarnation"),
("Parashuram","परशुराम","boy","Rama with the axe"),
("Raghunandan","रघुनंदन","boy","joy of the Raghu line"),
("Sitaram","सीताराम","boy","Rama with Sita"),
("Ram","राम","boy","the pleasing one"),
("Raghav","राघव","boy","descendant of Raghu"),
("Raghupati","रघुपति","boy","lord of the Raghus"),
("Janakinath","जानकीनाथ","boy","lord of Janaki"),
("Dasharathi","दाशरथि","boy","son of Dasharatha"),
("Kausalyanandan","कौसल्यानंदन","boy","son of Kausalya"),
("Kodandarama","कोदण्डराम","boy","Rama with the bow"),
("Sitapati","सीतापति","boy","husband of Sita"),
("Lakshman","लक्ष्मण","boy","the fortunate-marked"),
("Bharat","भारत","boy","the nurtured"),
("Shatrughna","शत्रुघ्न","boy","destroyer of foes"),
("Hanuman","हनुमान","boy","the strong-jawed"),
("Maruti","मारुति","boy","son of the wind"),
("Pavanputra","पवनपुत्र","boy","son of the wind"),
("Bajrangbali","बजरंगबली","boy","strong as thunderbolt"),
("Mahavir","महावीर","boy","the great hero"),
("Sankatmochan","संकटमोचन","boy","remover of troubles"),
("Anjaneya","आंजनेय","boy","son of Anjana"),
("Kesarinandan","केसरिनंदन","boy","son of Kesari"),
("Ramdoot","रामदूत","boy","Rama's messenger"),
("Balaji","बालाजी","boy","the strong lord"),
("Venkatesh","वेंकटेश","boy","lord of Venkata hill"),
("Srinivas","श्रीनिवास","boy","abode of Lakshmi"),
("Vishnu","विष्णु","boy","the all-pervader"),
("Chakradhar","चक्रधर","boy","discus bearer"),
("Shankhadhar","शंखधर","boy","conch bearer"),
("Gadadhar","गदाधर","boy","mace bearer"),
("Padmanabh","पद्मनाभ","boy","lotus-naveled"),
("Ranganath","रंगनाथ","boy","lord of the stage"),
("Vitthal","विठ्ठल","boy","standing on the brick"),
("Pandurang","पांडुरंग","boy","the white-hued"),
("Dattatreya","दत्तात्रेय","boy","son of Atri"),
("Narsimh","नरसिंह","boy","man-lion incarnation"),
("Hayagriva","हयग्रीव","boy","horse-necked Vishnu"),
("Shiv","शिव","boy","the auspicious one"),
("Shankar","शंकर","boy","giver of joy"),
("Shambhu","शम्भु","boy","the benevolent"),
("Mahesh","महेश","boy","the great lord"),
("Rudra","रुद्र","boy","the roarer"),
("Hara","हर","boy","the remover"),
("Mahadev","महादेव","boy","the great god"),
("Neelkanth","नीलकंठ","boy","blue-throated"),
("Gangadhar","गंगाधर","boy","bearer of the Ganga"),
("Chandrashekhar","चन्द्रशेखर","boy","moon-crested"),
("Trilochan","त्रिलोचन","boy","three-eyed"),
("Tripurari","त्रिपुरारि","boy","foe of the three cities"),
("Nataraj","नटराज","boy","king of dance"),
("Bholenath","भोलेनाथ","boy","the innocent lord"),
("Ashutosh","आशुतोष","boy","quickly pleased"),
("Pashupati","पशुपति","boy","lord of beings"),
("Vishwanath","विश्वनाथ","boy","lord of the universe"),
("Somnath","सोमनाथ","boy","lord of the moon"),
("Mallikarjun","मल्लिकार्जुन","boy","the jasmine-Arjuna"),
("Omkareshwar","ओंकारेश्वर","boy","lord of Om"),
("Rameshwar","रामेश्वर","boy","Rama's lord"),
("Kedarnath","केदारनाथ","boy","lord of Kedara"),
("Amarnath","अमरनाथ","boy","the immortal lord"),
("Kailashpati","कैलाशपति","boy","lord of Kailash"),
("Umapati","उमापति","boy","husband of Uma"),
("Girish","गिरीश","boy","lord of mountains"),
("Vyomkesh","व्योमकेश","boy","sky-haired"),
("Jatadhari","जटाधारी","boy","wearing matted locks"),
("Trishuldhari","त्रिशूलधारी","boy","trident bearer"),
("Damrudhar","डमरूधर","boy","drum bearer"),
("Digambar","दिगम्बर","boy","sky-clad"),
("Kapali","कपाली","boy","skull-bearer"),
("Bhairav","भैरव","boy","the terrible"),
("Kalbhairav","कालभैरव","boy","the black terrible"),
("Veerbhadra","वीरभद्र","boy","the heroic"),
("Dakshinamurti","दक्षिणामूर्ति","boy","the south-facing teacher"),
("Nageshwar","नागेश्वर","boy","lord of serpents"),
("Someshwar","सोमेश्वर","boy","lord of the moon"),
("Bhuteshwar","भूतेश्वर","boy","lord of spirits"),
("Yogesh","योगेश","boy","lord of yoga"),
("Shivansh","शिवांश","boy","part of Shiva"),
("Rudransh","रुद्रांश","boy","part of Rudra"),
("Shivam","शिवम्","boy","auspiciousness"),
("Shivay","शिवाय","boy","belonging to Shiva"),
("Tryambak","त्र्यम्बक","boy","three-eyed Shiva"),
("Mahakal","महाकाल","boy","the great time"),
("Bhootnath","भूतनाथ","boy","lord of spirits"),
("Shrikanth","श्रीकंठ","boy","beautiful-throated"),
("Durga","दुर्गा","girl","the invincible"),
("Uma","उमा","girl","the serene"),
("Parvati","पार्वती","girl","daughter of the mountain"),
("Gauri","गौरी","girl","the fair one"),
("Kali","काली","girl","the dark mother"),
("Bhavani","भवानी","girl","giver of life"),
("Ambika","अम्बिका","girl","the mother"),
("Jagdamba","जगदम्बा","girl","mother of the world"),
("Annapurna","अन्नपूर्णा","girl","full of food"),
("Meenakshi","मीनाक्षी","girl","fish-eyed"),
("Kamakshi","कामाक्षी","girl","loving-eyed"),
("Vishalakshi","विशालाक्षी","girl","wide-eyed"),
("Lalita","ललिता","girl","the playful"),
("Tripurasundari","त्रिपुरसुंदरी","girl","beauty of three worlds"),
("Rajarajeshwari","राजराजेश्वरी","girl","queen of queens"),
("Mahalakshmi","महालक्ष्मी","girl","the great Lakshmi"),
("Mahakali","महाकाली","girl","the great Kali"),
("Mahasaraswati","महासरस्वती","girl","the great Saraswati"),
("Chamunda","चामुण्डा","girl","slayer of demons"),
("Chandi","चण्डी","girl","the fierce"),
("Bhairavi","भैरवी","girl","the terrifying"),
("Baglamukhi","बगलामुखी","girl","the crane-faced"),
("Bhuvaneshwari","भुवनेश्वरी","girl","queen of the universe"),
("Dhumavati","धूमावती","girl","the smoky one"),
("Matangi","मातंगी","girl","the elephant goddess"),
("Kamala","कमला","girl","lotus goddess"),
("Shailputri","शैलपुत्री","girl","daughter of the mountain"),
("Brahmacharini","ब्रह्मचारिणी","girl","the ascetic maiden"),
("Chandraghanta","चन्द्रघण्टा","girl","bell-mooned warrior"),
("Kushmanda","कूष्माण्डा","girl","creator of the universe"),
("Skandamata","स्कन्दमाता","girl","mother of Skanda"),
("Katyayani","कात्यायनी","girl","daughter of Katyayana"),
("Kalaratri","कालरात्रि","girl","the dark night"),
("Mahagauri","महागौरी","girl","the great fair one"),
("Siddhidatri","सिद्धिदात्री","girl","giver of powers"),
("Shailaja","शैलजा","girl","mountain-born"),
("Aparna","अपर्णा","girl","the leafless ascetic"),
("Haimavati","हैमवती","girl","golden daughter of Himalaya"),
("Shivani","शिवानी","girl","Shiva's consort"),
("Rudrani","रुद्राणी","girl","Rudra's consort"),
("Maheshwari","महेश्वरी","girl","Mahesha's consort"),
("Sarvamangala","सर्वमंगला","girl","all-auspicious"),
("Shankari","शंकरी","girl","Shankara's consort"),
("Narayani","नारायणी","girl","Narayana's consort"),
("Vaishnavi","वैष्णवी","girl","devotee of Vishnu"),
("Brahmi","ब्राह्मी","girl","Brahma's power"),
("Kaumari","कौमारी","girl","the youthful"),
("Varahi","वाराही","girl","the boar goddess"),
("Indrani","इन्द्राणी","girl","Indra's queen"),
("Kaushiki","कौशिकी","girl","the radiant"),
("Mohini","मोहिनी","girl","the enchantress"),
("Tara","तारा","girl","the star goddess"),
("Shodashi","षोडशी","girl","the sixteen-year-old"),
("Mahamaya","महामाया","girl","the great illusion"),
("Yogmaya","योगमाया","girl","goddess of yoga"),
("Vindhyavasini","विन्ध्यवासिनी","girl","dweller of the Vindhyas"),
("Simhavahini","सिंहवाहिनी","girl","lion-rider"),
("Trinetri","त्रिनेत्री","girl","three-eyed goddess"),
("Chandika","चण्डिका","girl","the fierce goddess"),
("Ambaji","अम्बाजी","girl","the revered mother"),
("Santoshi","संतोषी","girl","goddess of contentment"),
("Sheetala","शीतला","girl","the cooling goddess"),
("Lakshmi","लक्ष्मी","girl","goddess of fortune"),
("Shri","श्री","girl","radiance"),
("Padma","पद्मा","girl","the lotus"),
("Padmavati","पद्मावती","girl","lotus lady"),
("Ramaa","रमा","girl","the pleasing"),
("Haripriya","हरिप्रिया","girl","beloved of Hari"),
("Vishnupriya","विष्णुप्रिया","girl","beloved of Vishnu"),
("Sridevi","श्रीदेवी","girl","goddess of radiance"),
("Bhargavi","भार्गवी","girl","daughter of Bhrigu"),
("Jaladhija","जलधिजा","girl","ocean-born"),
("Samudratanaya","समुद्रतनया","girl","daughter of the ocean"),
("Indira","इन्दिरा","girl","the splendid"),
("Lokamata","लोकमाता","girl","mother of the world"),
("Varalakshmi","वरलक्ष्मी","girl","boon-giving Lakshmi"),
("Dhanalakshmi","धनलक्ष्मी","girl","goddess of wealth"),
("Dhanyalakshmi","धान्यलक्ष्मी","girl","goddess of grain"),
("Gajalakshmi","गजलक्ष्मी","girl","Lakshmi with elephants"),
("Santanlakshmi","संतानलक्ष्मी","girl","goddess of progeny"),
("Vijayalakshmi","विजयलक्ष्मी","girl","goddess of victory"),
("Vidyalakshmi","विद्यालक्ष्मी","girl","goddess of learning"),
("Adilakshmi","आदिलक्ष्मी","girl","the primal Lakshmi"),
("Saraswati","सरस्वती","girl","goddess of learning"),
("Sharada","शारदा","girl","giver of essence"),
("Vani","वाणी","girl","speech"),
("Bharati","भारती","girl","eloquence"),
("Veenapani","वीणापाणि","girl","veena-handed"),
("Hansvahini","हंसवाहिनी","girl","swan-rider"),
("Vagdevi","वाग्देवी","girl","goddess of speech"),
("Vidyadayini","विद्यादायिनी","girl","giver of knowledge"),
("Shwetambara","श्वेताम्बरा","girl","white-robed"),
("Mahashweta","महाश्वेता","girl","greatly fair"),
("Ganesh","गणेश","boy","lord of hosts"),
("Ganapati","गणपति","boy","lord of hosts"),
("Vinayak","विनायक","boy","the remover"),
("Vighnesh","विघ्नेश","boy","lord of obstacles"),
("Vighnaharta","विघ्नहर्ता","boy","remover of obstacles"),
("Lambodar","लम्बोदर","boy","pot-bellied"),
("Ekdant","एकदन्त","boy","single-tusked"),
("Vakratunda","वक्रतुण्ड","boy","curved-trunked"),
("Gajanan","गजानन","boy","elephant-faced"),
("Gaurinandan","गौरीनंदन","boy","Gauri's son"),
("Shivnandan","शिवनंदन","boy","Shiva's son"),
("Umaputra","उमापुत्र","boy","Uma's son"),
("Siddhivinayak","सिद्धिविनायक","boy","giver of success"),
("Mahaganapati","महागणपति","boy","the great Ganapati"),
("Heramba","हेरम्ब","boy","the protector"),
("Dhumraketu","धूम्रकेतु","boy","smoke-bannered"),
("Bhalchandra","भालचन्द्र","boy","moon-foreheaded"),
("Sumukh","सुमुख","boy","beautiful-faced"),
("Shupkarna","शूपकर्ण","boy","large-eared"),
("Ganadhipa","गणाधिप","boy","chief of hosts"),
("Surya","सूर्य","boy","the sun"),
("Aditya","आदित्य","boy","son of Aditi"),
("Bhaskar","भास्कर","boy","light-maker"),
("Divakar","दिवाकर","boy","day-maker"),
("Ravi","रवि","boy","the radiant"),
("Martand","मार्तण्ड","boy","the sun"),
("Mitra","मित्र","boy","the friend"),
("Pushan","पूषन","boy","the nourisher"),
("Vivasvan","विवस्वान","boy","the brilliant"),
("Indra","इन्द्र","boy","king of gods"),
("Mahendra","महेन्द्र","boy","the great Indra"),
("Devendra","देवेन्द्र","boy","chief of gods"),
("Surendra","सुरेन्द्र","boy","chief of gods"),
("Upendra","उपेन्द्र","boy","Vishnu, Indra's brother"),
("Sachipati","शचीपति","boy","husband of Shachi"),
("Vajradhar","वज्रधर","boy","thunderbolt bearer"),
("Agni","अग्नि","boy","fire"),
("Vayu","वायु","boy","wind"),
("Varun","वरुण","boy","lord of waters"),
("Kuber","कुबेर","boy","lord of wealth"),
("Dhanpati","धनपति","boy","lord of wealth"),
("Chitragupta","चित्रगुप्त","boy","the record keeper"),
("Kartikeya","कार्तिकेय","boy","son of the Krittikas"),
("Skanda","स्कन्द","boy","the attacker"),
("Subramanya","सुब्रह्मण्य","boy","the auspicious"),
("Murugan","मुरुगन","boy","the beautiful"),
("Shanmukha","षण्मुख","boy","six-faced"),
("Senapati","सेनापति","boy","army chief"),
("Mahasena","महासेन","boy","great army"),
("Kumara","कुमार","boy","the youth"),
("Dattatreya","दत्तात्रेय","boy","son of Atri"),
("Shani","शनि","boy","Saturn"),
("Mangal","मंगल","boy","Mars"),
("Brihaspati","बृहस्पति","boy","Jupiter"),
("Budha","बुध","boy","Mercury"),
("Arun","अरुण","boy","dawn"),
]
