# Hand-curated seed names: epic figures, sages, nature. Format: (latin, devanagari, gender, english meaning)
SEEDS2 = [
("Arjun","अर्जुन","boy","the bright"),
("Yudhishthir","युधिष्ठिर","boy","firm in battle"),
("Bhim","भीम","boy","the terrible"),
("Nakul","नकुल","boy","the handsome"),
("Sahadev","सहदेव","boy","with the gods"),
("Abhimanyu","अभिमन्यु","boy","the angry"),
("Parikshit","परीक्षित","boy","the examiner"),
("Janamejaya","जनमेजय","boy","victorious king"),
("Shantanu","शांतनु","boy","the peaceful"),
("Bhishma","भीष्म","boy","the terrible vow"),
("Drona","द्रोण","boy","the bucket-born"),
("Kripa","कृप","boy","grace"),
("Ashwatthama","अश्वत्थामा","boy","horse-voiced"),
("Karna","कर्ण","boy","the ear"),
("Duryodhan","दुर्योधन","boy","hard to conquer"),
("Dushasan","दुःशासन","boy","hard to rule"),
("Shakuni","शकुनि","boy","the bird"),
("Vidur","विदुर","boy","the wise"),
("Dhritarashtra","धृतराष्ट्र","boy","kingdom-bearer"),
("Pandu","पाण्डु","boy","the pale"),
("Dasharath","दशरथ","boy","ten chariots"),
("Raghu","रघु","boy","the swift"),
("Dilip","दिलीप","boy","protector"),
("Aja","अज","boy","the unborn"),
("Harishchandra","हरिश्चन्द्र","boy","golden moon"),
("Bhagirath","भगीरथ","boy","who brought the Ganga"),
("Ikshvaku","इक्ष्वाकु","boy","the sugarcane"),
("Manu","मनु","boy","the thinker"),
("Prithu","पृथु","boy","the broad"),
("Mandhata","मान्धाता","boy","the honored"),
("Shibi","शिबि","boy","the hospitable"),
("Rantideva","रंतिदेव","boy","god of delight"),
("Nahusha","नहुष","boy","the binder"),
("Yayati","ययाति","boy","the traveler"),
("Puru","पुरु","boy","the abundant"),
("Dushyant","दुष्यंत","boy","destroyer of evil"),
("Rishyashringa","ऋष्यशृंग","boy","deer-horned"),
("Eklavya","एकलव्य","boy","the devoted archer"),
("Ghatotkach","घटोत्कच","boy","son of Hidimba"),
("Pradyumna","प्रद्युम्न","boy","the mighty"),
("Aniruddha","अनिरुद्ध","boy","the unobstructed"),
("Samba","साम्ब","boy","son of Krishna"),
("Balaram","बलराम","boy","strong Rama"),
("Vibhishan","विभीषण","boy","the terrible"),
("Sugriv","सुग्रीव","boy","beautiful-necked"),
("Jambavan","जाम्बवान","boy","the bear king"),
("Angad","अंगद","boy","the ornament"),
("Nal","नल","boy","the reed"),
("Jatayu","जटायु","boy","the vulture king"),
("Sita","सीता","girl","the furrow"),
("Janaki","जानकी","girl","daughter of Janaka"),
("Maithili","मैथिली","girl","princess of Mithila"),
("Vaidehi","वैदेही","girl","princess of Videha"),
("Bhumija","भूमिजा","girl","earth-born"),
("Ramapriya","रामप्रिया","girl","beloved of Rama"),
("Draupadi","द्रौपदी","girl","daughter of Drupada"),
("Panchali","पांचाली","girl","princess of Panchala"),
("Yagyaseni","यज्ञसेनी","girl","fire-born"),
("Savitri","सावित्री","girl","daughter of the sun"),
("Damayanti","दमयंती","girl","the subduer"),
("Shakuntala","शकुंतला","girl","bird-protected"),
("Anusuya","अनसूया","girl","without envy"),
("Arundhati","अरुंधती","girl","the faithful star-wife"),
("Lopamudra","लोपामुद्रा","girl","the sage's wife"),
("Gargi","गार्गी","girl","the scholar"),
("Maitreyi","मैत्रेयी","girl","the wise woman"),
("Sulabha","सुलभा","girl","the eloquent"),
("Mandodari","मंदोदरी","girl","Ravana's queen"),
("Kaikeyi","कैकेयी","girl","Dasharatha's queen"),
("Kaushalya","कौशल्या","girl","Rama's mother"),
("Sumitra","सुमित्रा","girl","Lakshmana's mother"),
("Shabari","शबरी","girl","the devotee"),
("Ahalya","अहिल्या","girl","Gautama's wife"),
("Renuka","रेणुका","girl","Parashurama's mother"),
("Devaki","देवकी","girl","Krishna's mother"),
("Yashoda","यशोदा","girl","Krishna's foster mother"),
("Rohini","रोहिणी","girl","Balarama's mother"),
("Subhadra","सुभद्रा","girl","Arjuna's wife"),
("Uttara","उत्तरा","girl","Abhimanyu's wife"),
("Chitrangada","चित्रांगदा","girl","Arjuna's wife"),
("Ulupi","उलूपी","girl","the Naga princess"),
("Hidimba","हिडिम्बा","girl","Bhima's wife"),
("Kunti","कुंती","girl","mother of the Pandavas"),
("Madri","माद्री","girl","Pandu's queen"),
("Gandhari","गांधारी","girl","mother of Kauravas"),
("Rukmini","रुक्मिणी","girl","Krishna's queen"),
("Satyabhama","सत्यभामा","girl","Krishna's queen"),
("Jambavati","जाम्बवती","girl","Krishna's queen"),
("Meera","मीरा","girl","the devotee"),
("Andal","आंडाल","girl","the devotee saint"),
("Radha","राधा","girl","the beloved"),
("Revati","रेवती","girl","Balarama's wife"),
("Satyavati","सत्यवती","girl","the truthful"),
("Ambalika","अम्बालिका","girl","mother of Pandu"),
("Devayani","देवयानी","girl","daughter of Shukra"),
("Sharmishtha","शर्मिष्ठा","girl","the modest"),
("Vashishtha","वशिष्ठ","boy","the most excellent"),
("Vishwamitra","विश्वामित्र","boy","friend of the world"),
("Atri","अत्रि","boy","the devourer"),
("Gautam","गौतम","boy","remover of darkness"),
("Kashyap","कश्यप","boy","the tortoise"),
("Bhrigu","भृगु","boy","the radiant"),
("Angiras","अंगिरस","boy","the fiery"),
("Pulastya","पुलस्त्य","boy","the listener"),
("Marichi","मरीचि","boy","ray of light"),
("Daksha","दक्ष","boy","the skilled"),
("Narada","नारद","boy","giver of knowledge"),
("Valmiki","वाल्मीकि","boy","the anthill-born"),
("Vyasa","व्यास","boy","the compiler"),
("Shukadeva","शुकदेव","boy","divine parrot"),
("Parashara","पराशर","boy","the destroyer"),
("Jaimini","जैमिनि","boy","the victorious"),
("Yagyavalkya","याज्ञवल्क्य","boy","of the sacrifice"),
("Uddalaka","उद्दालक","boy","the elevated"),
("Shvetaketu","श्वेतकेतु","boy","white-bannered"),
("Nachiketa","नचिकेता","boy","the seeker"),
("Kapila","कपिल","boy","the tawny"),
("Kanada","कणाद","boy","atom-eater"),
("Patanjali","पतंजलि","boy","the fallen grace"),
("Panini","पाणिनि","boy","the grammarian"),
("Charaka","चरक","boy","the wanderer"),
("Sushruta","सुश्रुत","boy","well-heard"),
("Aryabhata","आर्यभट","boy","the noble scholar"),
("Varahamihira","वराहमिहिर","boy","sun-boar"),
("Brahmagupta","ब्रह्मगुप्त","boy","protected by Brahma"),
("Bhaskaracharya","भास्कराचार्य","boy","teacher of light"),
("Chanakya","चाणक्य","boy","the shrewd"),
("Kautilya","कौटिल्य","boy","the diplomat"),
("Kalidasa","कालिदास","boy","servant of Kali"),
("Bhavabhuti","भवभूति","boy","the poet"),
("Tulsidas","तुलसीदास","boy","servant of Tulsi"),
("Surdas","सूरदास","boy","servant of Surya"),
("Kabir","कबीर","boy","the great"),
("Godavari","गोदावरी","girl","the Godavari river"),
("Shipra","शिप्रा","girl","the Shipra river"),
("Tapti","ताप्ती","girl","the Tapti river"),
("Himani","हिमानी","girl","snow goddess"),
("Shaila","शैला","girl","mountain girl"),
("Girija","गिरिजा","girl","mountain-born"),
("Kamal","कमल","boy","lotus"),
("Kumud","कुमुद","boy","lotus"),
("Nalini","नलिनी","girl","lotus"),
("Kumudini","कुमुदिनी","girl","lotus pond"),
("Padmini","पद्मिनी","girl","lotus lady"),
("Kamalini","कमलिनी","girl","lotus pond"),
("Mrinal","मृणाल","boy","lotus stalk"),
("Mrinalini","मृणालिनी","girl","lotus stalk"),
("Chand","चन्द्र","boy","the moon"),
("Chandrika","चन्द्रिका","girl","moonlight"),
("Nakshatra","नक्षत्र","girl","constellation"),
("Ashwini","अश्विनी","girl","the first star"),
("Bharani","भरणी","girl","the second star"),
("Pushya","पुष्य","boy","the nourishing star"),
("Chitra","चित्रा","girl","the bright star"),
("Swati","स्वाति","girl","the pearl star"),
("Vishakha","विशाखा","girl","the branched star"),
("Anuradha","अनुराधा","girl","the devoted star"),
("Shravana","श्रवण","boy","the listening star"),
("Usha","उषा","girl","dawn"),
("Aruna","अरुणा","girl","dawn"),
("Sandhya","संध्या","girl","twilight"),
("Vasant","वसन्त","boy","spring"),
("Sharad","शरद","boy","autumn"),
("Shishir","शिशिर","boy","winter"),
("Prakriti","प्रकृति","girl","nature"),
("Bhumi","भूमि","girl","earth"),
("Ila","इला","girl","earth"),
("Urvi","उर्वी","girl","earth"),
("Vasudha","वसुधा","girl","earth"),
("Dhara","धरा","girl","earth"),
("Kshitija","क्षितिजा","girl","earth-born"),
("Akash","आकाश","boy","sky"),
("Gagan","गगन","boy","sky"),
("Vyom","व्योम","boy","sky"),
("Pavan","पवन","boy","wind"),
("Sameer","समीर","boy","breeze"),
("Marut","मरुत्","boy","wind"),
("Prakash","प्रकाश","boy","light"),
("Ujjwal","उज्ज्वल","boy","bright"),
("Tejas","तेजस्","boy","radiance"),
("Deepak","दीपक","boy","lamp"),
("Diya","दीया","girl","lamp"),
("Jyoti","ज्योति","girl","flame"),
("Shikha","शिखा","girl","flame"),
("Jwala","ज्वाला","girl","flame"),
("Champa","चम्पा","girl","frangipani"),
("Bela","बेला","girl","jasmine"),
("Gulab","गुलाब","boy","rose"),
("Maina","मैना","girl","the myna"),
("Hiran","हिरण","boy","deer"),
("Simha","सिंह","boy","lion"),
("Gaja","गज","boy","elephant"),
("Ashva","अश्व","boy","horse"),
("Nandi","नन्दी","boy","Shiva's bull"),
("Surabhi","सुरभि","girl","the fragrant cow"),
("Apsara","अप्सरा","girl","celestial nymph"),
("Menaka","मेनका","girl","the apsara"),
("Urvashi","उर्वशी","girl","the apsara"),
("Rambha","रम्भा","girl","the apsara"),
("Tilottama","तिलोत्तमा","girl","the peerless apsara"),
("Aranyani","अरण्यानी","girl","goddess of forests"),
("Tulsi","तुलसी","girl","holy basil"),
("Chandan","चन्दन","boy","sandalwood"),
("Kesar","केसर","boy","saffron"),
("Ela","एला","girl","cardamom"),
("Soma","सोम","boy","the moon draught"),
("Amrita","अमृता","girl","nectar"),
("Amrit","अमृत","boy","nectar"),
("Sudha","सुधा","girl","nectar"),
("Piyush","पीयूष","boy","nectar"),
("Madhu","मधु","boy","honey"),
("Madhuri","माधुरी","girl","sweetness"),
("Madhur","मधुर","boy","sweet"),
("Rasa","रस","boy","essence"),
("Rupa","रूपा","girl","beauty"),
("Manas","मानस","boy","mind"),
("Buddhi","बुद्धि","girl","intellect"),
("Chitta","चित्त","boy","consciousness"),
("Sattva","सत्त्व","boy","purity"),
("Veda","वेद","boy","knowledge"),
("Sutra","सूत्र","boy","thread"),
("Lipi","लिपि","girl","script"),
("Akshara","अक्षरा","girl","letter"),
("Kavya","काव्या","girl","poetry"),
("Nritta","नृत्त","boy","dance"),
("Nritya","नृत्य","boy","dance"),
("Tandava","ताण्डव","boy","Shiva's dance"),
("Lasya","लास्य","girl","Parvati's dance"),
("Laya","लय","boy","rhythm"),
("Tala","ताल","boy","rhythm"),
("Raga","राग","boy","melody"),
("Ragini","रागिनी","girl","melody"),
("Svara","स्वर","boy","note"),
("Shruti","श्रुति","girl","heard scripture"),
("Smriti","स्मृति","girl","memory"),
("Gita","गीता","girl","song"),
("Sangita","संगीता","girl","music"),
("Veena","वीणा","girl","lute"),
("Venu","वेणु","boy","flute"),
("Shankha","शंख","boy","conch"),
("Bansuri","बाँसुरी","girl","flute"),
]
